services:
  homeassistant:
    container_name: homeassistant
    build:
      context: .  # Указываем, что сборка будет происходить из текущей директории
      dockerfile: Dockerfile  # Используем наш Dockerfile для сборки
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Europe/Moscow
    volumes:
      - "D:/Radio/SmartHome/Home assistant dev/homeassistant-energomera-electricity-meter:/config"
    ports:
      - "8123:8123"
